### ISSUE TITLE
melancholianna request

### ISSUE THREAD

**Issue by NekoDevs180** [Cicini/melancholianna#1]
Thanks!

**Comment by Cicini** [comment]
> Hi @Cicini , is it possible to have the complete project and an exe version of the game? If possible also an email address or other types of contacts. Thank you and good day!

The original file for the game is an exe version, but this project was originally uploaded to be accessible on browsers, and  you should be able to find out how to download it by searching the keyword 'melancholianna' on the internet (e.g. google).
